config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  
  
  get 'register', to: 'users#new'
  
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  
  resources :categories, only: [:new, :create, :show]
  
  resources :posts, except: [:destroy] do
    member do
      post :vote
    end
    
    resources :comments, only: [:create] do
      member do
        post :vote
      end
    end
  end
  
  resources :users, only: [:create, :edit, :update, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  
  def total_votes
    up_votes - down_votes
  end
  
  def up_votes
    self.votes.where(vote: true).size
  end
  
  def down_votes
    self.votes.where(vote: false).size
  end
end

app/models/category.rb
class Category < ApplicationRecord 
  has_many :post_categories
  has_many :posts, through: :post_categories
  
  validates :name, presence: true, uniqueness: true
end

app/models/comment.rb
class Comment < ApplicationRecord 
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  belongs_to :post
  has_many :votes, as: :voteable
  
  validates :body, presence: true, length: {minimum: 5}
end

app/models/post.rb
class Post < ApplicationRecord 
  belongs_to :creator, foreign_key: 'user_id', class_name: 'User'
  has_many :comments
  has_many :post_categories
  has_many :categories, through: :post_categories
  has_many :votes, as: :voteable
  
  validates :title, presence: true, length: { minimum: 5}
  validates :description, presence: true
  validates :url, presence: true, uniqueness: true
  
end

app/models/post_category.rb
class PostCategory < ApplicationRecord 
  belongs_to :post
  belongs_to :category 
end

app/models/user.rb
class User < ApplicationRecord 
  has_many :posts
  has_many :comments
  has_many :votes
  
  has_secure_password validations: false
  
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true, on: :create, length: {minimum: 3}
end

app/models/vote.rb
class Vote < ApplicationRecord 
  belongs_to :creator, class_name: 'User', foreign_key: 'user_id'
  belongs_to :voteable, polymorphic: true
  
  validates_uniqueness_of :creator, scope: [:voteable_id, :voteable_type]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  
  helper_method :current_user, :logged_in?
  
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  
  def logged_in?
    !!current_user
  end
  
  def require_user
    unless logged_in?
      flash[:error] = "must be logged in to do so"
      redirect_to root_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :require_user, only: [:new, :create]

  def index
    @categories = Category.all
  end
  
  def show
    @category = Category.find(params[:id])
  end
  
  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(categories_params)
    
    if @category.save
      flash[:notice] = 'You added a category'
      redirect_to root_path
    else
      flash[:notice] = 'You failed'
      render :new
    end
  end
  
  def edit
    @category = Category.find(params[:id])
  end
  
  def update
    @category = Category.find(params[:id])
    
    if @category.update(categories_params)
      flash[:notice] = 'You updated a category'
      redirect_to categories_path
    else 
      flash[:notice] = 'You failed'
      render :edit
    end
  end
  
  def destroy
    @category = Category.find(params[:id])
    @category.destroy
    flash[:notice] = 'You deleted this category'
    redirect_to categories_path
    
  end
  
  private
  
  def categories_params
    params.require(:category).permit(:name)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :require_user
  
  def vote
    comment = Comment.find(params[:id])
    @vote = Vote.create(vote: params[:vote], creator: current_user, voteable: comment)
    
    if @vote.valid?
      flash[:notice] = 'Your vote is counted.'
    else
      flash[:error] = 'You can vote only once'
    end
  
    redirect_back(fallback_location: root_path)
  end

  def create
    
    @post = Post.find(params[:post_id])
    @comment = @post.comments.build(params.require(:comment).permit(:body))
    @comment.creator = current_user
    
    if @comment.save
      flash[:notice] = 'Comment saved'
      redirect_to post_path(@post)
    else
      flash[:notice] = 'Comment not saved'
      render 'posts/show'
    end
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :vote]
  before_action :require_user, except: [:index, :show]
  
  def vote
    @vote = Vote.create(voteable: @post, creator: current_user, vote: params[:vote])
    
    if @vote.valid?
      flash[:notice] = 'Your vote was counted.'
    else
      flash[:error] = "You can vote only once."
    end
    
    redirect_back(fallback_location: root_path)
  end

  def index
    # get all posts and sort them by votes in descending order
    @posts = Post.all.sort_by{|post| post.total_votes }.reverse
    render 'index'
  end
  
  def show
    @comment = Comment.new
  end
  
  def new
    @post = Post.new
  end
  
  def create
    @post = Post.new(post_params)
    @post.creator = current_user
    
    if @post.save
      flash[:notice] = 'Your post was created'
      redirect_to posts_path
    else
      flash[:notice] = 'Your post was not created'
      render :new
    end
    
  end
  
  def edit
    render :edit
  end
  
  def update
    if @post.update(post_params)
      flash[:notice] = 'Your post was updated'
      redirect_to post_path(@post)
    else 
      flash[:notice] = 'Your post was not updated'
      render :edit
    end
  end
  
  private
  
  def post_params
    params.require(:post).permit(:title, :url, :description, category_ids: [])
  end
  
  def set_post
    @post = Post.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  
  def create
    user = User.find_by(username: params[:username])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:notice] = 'You are logged in'
      redirect_to root_path
    else
      flash[:error] = "There's soemthing wrong with your username or password."
      redirect_to register_path
    end
  end
 
  def destroy
    session[:user_id] = nil
    flash[:notice] = 'You are logged out.'
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  before_action :require_same_user, only: [:edit, :update]

  def new
    @user = User.new
  end
  
  def show
    @user = User.find(session[:user_id])
    @posts = @user.posts
    @comments = @user.comments    
  end
  
  def create
    @user = User.new(user_params)
    
    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = 'You are registered.'
      redirect_to root_path
    else
      render :new
    end
  end
  
  def edit
  end
  
  def update
    if @user.update(user_params)
      flash[:notice] = 'Your profile is updated'
      redirect_to root_path
    else
      render :edit
    end
  
  end
  
  private
  
  def user_params
    params.require(:user).permit(:username, :password)
  end
  
  def set_user
    @user = User.find(params[:id])
  end
  
  def require_same_user
    if current_user != @user
      flash[:error] = 'You do not have access'
      redirect_to root_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def fix_url(str)
    str.starts_with?('http://') ? str : "http://#{str}"
  end
  
  def display_datetime(dateObj)
    dateObj.strftime("%m/%d/%Y %l:%M%P %Z")
  end
end

app/views/categories/_category.html.erb
<span class='badge'><%= link_to category.name, category_path(category) %></span>

app/views/categories/_form.html.erb
<%= render 'shared/error_messages', error_object: @category %>

<div class='wrapper'>
  <%= form_for @category do |f| %>
    <%=f.label :name %>
    <%= f.text_field :name %>
    </br>
    <%= f.submit(@category.new_record? ? 'Create Category' : 'Update Category', class: 'btn btn-primary') %>

  <% end %>
</div>

app/views/categories/edit.html.erb
<h4>Edit a Category</h4>

<%= render 'form' %>

app/views/categories/index.html.erb
<%= render 'shared/content_title', title: 'All Categories' %>

<ul>
  <% @categories.each do |category| %>
    <div class='row'>
      <li>
        <%= category.name %> 
        | <%= link_to 'edit', edit_category_path(category) %> 
        | <%= link_to 'delete', category_path(category), data: { confirm: 'Are you sure?'}, method: :delete %>
      </li>
    </div>
  <% end %>
  <%= link_to 'Add Category', new_category_path %>
</ul>

app/views/categories/new.html.erb
<%= render 'shared/content_title', title: 'New Category' %>

<%= render 'form' %>

app/views/categories/show.html.erb
<% all_posts = link_to('All Posts', posts_path) %>

<%= render 'shared/content_title', title: "#{all_posts} &raquo; #{@category.name}".html_safe %>

<% @category.posts.each do |post| %>
  <%= render 'posts/post', post: post %>
<% end %>

app/views/comments/_comment.html.erb
<% show_post ||= false %>
<div class='row'>
<% if logged_in? %>
  <div class='span3 well text-center' style='width:40px; background: lightgray; margin: 5px;'>
    <%= link_to vote_post_comment_path(comment.post, comment, vote: true), method: 'post' do %>
      <i class='icon-arrow-up'> :)</i>
    <% end %>
    </br>
    <%= comment.total_votes %> 
    </br>
    <%= link_to vote_post_comment_path(comment.post, comment, vote: false), method: 'post' do %>
      <i id='caret'> :( </i>
      
    <% end %>
  </div>
<% end %>
<div class='well span8'>
  <em>"<%= comment.body %>"</em>
  <% if show_post %>
    on <%= link_to comment.post.title, post_path(comment.post) %>
  <% end %>
  <br/>
  by <%= link_to comment.creator.username, '' %>
</div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == "notice" ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<ul class="nav">
  <li>
    <%= link_to "Postit!", root_path, class: 'btn btn-success btn-small' %>
  </li>
  <li style="width:15px"></li>
  <li>
    <div class='btn-group nav_item'>
      <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
        Categories <span class='caret'></span>
        
      <% end %>
      <ul class='dropdown-menu'>
        <% Category.all.each do |category| %>
          <li><%= link_to category.name, category_path(category) %></li>
        <% end %>
        <% if logged_in? %>
          <li class='divider'></li>
          <li>
            <%= link_to(new_category_path) do %>
              <i class='icon-plus'></i>
              New Category
            <% end %>
          </li>
        <% end %>
      </ul>
    </div>
  </li>
  <li style="width:15px"></li>
  <li>
  <% if logged_in? %>
  
    <li>
      <%= link_to 'New Post', new_post_path, class: 'btn btn-success btn-small' %>
     </li>
    <li style="width:15px"></li>
    <div class='btn-group nav_item'>
      <%= link_to '#', class: 'btn btn-small dropdown-toggle', 'data-toggle' => 'dropdown' do %>
        <%= current_user.username %><span class='caret'></span>
      <% end %>
      <ul class='dropdown-menu'>
        <li>
          <%= link_to edit_user_path(current_user) do %>
            <i class='icon-pencil'></i>
            edit profile
          <% end %>
        </li>
        <li>
          <%= link_to "Show Profile", user_path(current_user), class: 'btn btn-success btn-small' %>
        </li>
        <li>
          <%= link_to "Log Out", logout_path, class: 'btn btn-success btn-small' %>
        </li>
      </ul>
    </div>
    
  <% else %> 
  
    <li>
      <%= link_to "Register", register_path, class: 'btn btn-success btn-small' %>
    </li>
    <li>
      <%= link_to "Log in", login_path, class: 'btn btn-success btn-small' %>
    </li>
    
  <% end %>
  
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tealeaf Academy - Postit</title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header>
      <div class="navbar">
        <div class="navbar-inner">
          <div class="container">
            <%= render 'layouts/navigation' %>
          </div>
        </div>
      </div>
    </header>
    <div id="main" role="main">
      <div class="container">
         <div class="row">
          <div class="span12">
            <%= render 'layouts/messages' %>
            <%= yield %>
          </div>
        </div>
        <footer>
        </footer>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/posts/_form.html.erb
<%= render 'shared/error_messages', error_object: @post %>

<div class='well'>
  <%= form_for @post do |f| %>
    <%=f.label :title %>
    <%= f.text_field :title %>
    </br>
    <%=f.label :url %>
    <%= f.text_field :url %>
    </br>
    <%=f.label :description %>
    <%= f.text_area :description, rows: 5  %>
    <br/>
    <div class='control-group'>
      <%= f.label 'Categorie Options' %>
      <%= f.collection_check_boxes :category_ids, Category.all, :id, :name do |cb| %>
        <% cb.label(class: 'checkbox inline') {cb.check_box(class: 'checkbox') + cb.text} %>
      <% end %>
    </div>
    </br>
    <%= f.submit(@post.new_record? ? 'Create Post' : 'Update Post', class: 'btn btn-primary') %>

  <% end %>
</div>

app/views/posts/_post.html.erb
<div class='row' >
<% if logged_in? %>
  <div class='span3 well text-center' style='width:40px; background: lightgray; margin: 5px;'>
    <%= link_to vote_post_path(post, vote: true), method: 'post' do %>
      <i class='icon-arrow-up'> :)</i>
    <% end %>
    </br>
    <%= post.total_votes %> 
    </br>
    <%= link_to vote_post_path(post, vote: false), method: 'post' do %>
      <i class='caret'> :( </i>
      
    <% end %>
  </div>
<% else %>
  <div class='span3 well text-center' style='width:40px; background: lightgray; margin: 5px;'>
    </br>
    <%= post.total_votes %> 
  </div>
<% end %>
  <div class='span8 well'>
    <%= render post.categories %>
    <h4><%= link_to post.title, fix_url(post.url) %></h4>
    <h4><%= post.description %></h4>
    (<%= link_to 'edit', edit_post_path(post) if logged_in? %>)
    <p>
      <small>at <%= display_datetime(post.created_at) %></small>
      
    </p>
    <small>
      <span>
        <%= link_to("#{post.comments.size} comments", post_path(post)) %>
      </span>
    </small>
  </div>
</div>

app/views/posts/edit.html.erb
<h4>Edit a Post</h4>

<%= render 'form' %>

app/views/posts/index.html.erb
<%= render 'shared/content_title', title: 'All Posts' %>


<ul>
  <% @posts.each do |post| %>
    <%= render 'post', post: post %>
  <% end %>
</ul>

app/views/posts/new.html.erb
<h4>Create a Post</h4>

<%= render 'form' %>

app/views/posts/show.html.erb
<h4>Hi there, you're viewing <%= link_to @post.title, fix_url(@post.url) %>

<% if logged_in? %>
  <p class='pull-right'>
    [<%= link_to 'edit this post', edit_post_path(@post) %>]
  </p>
<% end %>

<%= render @post.categories %> 

<%= render 'shared/content_title', title: @post.title %>

<p>
<%= @post.description %>
<hr/>
</p>

<%= link_to 'go back to all posts', posts_path %>

<% if logged_in? %>
  <h5>Create a comment:</h5>
  <%= form_for [@post, @comment] do |f| %>
  <%= render 'shared/error_messages', error_object: @comment %>
    <div class='control-group'>
      <%= f.text_area :body %>
      <br/>
    </div>
      <%= f.submit 'Create Comment', class: 'btn btn-primary' %>
  <% end %>
<% end %>

<h5>Comments:</h5>
<% @post.comments.each do |comment| %>
    <%= render 'comments/comment', comment: comment %>
<% end %>

app/views/shared/_content_title.html.erb
<p class='lead'>
  <%= title %>
  <hr/>
</p>

app/views/shared/_error_messages.erb
<% if error_object.errors.any? %>
  <div class='row'>
    <div class='alert alert-error span8'>
      <h5> Please fix these errors</h5>
        <ul>
          <% error_object.errors.full_messages.each do |error| %>
            <li><%= error %></li>
          <% end %>
        </ul>
    </div>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= render 'shared/error_messages', error_object: @user %>

<div class='well'>
  <%= form_for @user do |f| %>
    <%=f.label :username %>
    <%= f.text_field :username %>
    </br>
    <%=f.label :password %>
    <%= f.password_field :password %>
    </br>
    <%= f.submit(@user.new_record? ? 'Register' : 'Update Profile', class: 'btn btn-primary') %>

  <% end %>
</div>

app/views/users/edit.html.erb
<h4>Edit your profile</h4>

<%= render 'form' %>

app/views/users/new.html.erb
<h4>Register</h4>

<%= render 'form' %>

app/views/users/show.html.erb
<%= render 'shared/content_title', title: "Profile: #{@user.username}" %>

<div class='working'>
  <p>Username: <%= @user.username %> </p>
</div>

<p><strong><%= @user.username %>'s Activity</strong></p>

<ul class='nav nav-tabs'>
  <li class='<%= 'active' if params[:tab].nil? %>'>
    <%= link_to "Posts (#{@user.posts.size})", user_path(@user) %>
  </li>
  <li class='<%= 'active' if params[:tab] == 'comments' %>'>
    <%= link_to "Comments (#{@user.comments.size})", user_path(@user, tab: 'comments') %>
  </li>
</ul>

<% if params[:tab].nil? %>
  <h5>Posts:</h5>
  <% @user.posts.each do |post| %>
    <%= render 'posts/post', post: post %> 
  <% end %>
<% elsif %>
  <h5>Comments:</h5>
    <% @user.comments.each do |comment| %>
      <%= render 'comments/comment', comment: comment, show_post: true %>
    <% end %>
<% end %>